# Generated by Django 4.2.3 on 2023-08-15 07:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='ادرس'),
            preserve_default=False,
        ),
    ]
