# Generated by Django 4.2.3 on 2023-08-18 16:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_special_suer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='special_suer',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='کاربر ویژه تا'),
        ),
    ]
