# Generated by Django 4.2.5 on 2023-09-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_special_suer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, default='media/images/users/account.png', upload_to='media/images/users/', verbose_name='تصویر'),
        ),
    ]
