# Generated by Django 4.2.5 on 2023-09-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_ip_address_alter_article_managers_article_ips'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='IPs',
            field=models.ManyToManyField(blank=True, related_name='article', to='blog.ip_address'),
        ),
    ]
